name: Tests Lowest Dependencies

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    test_lowest_dependencies:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   run: git fetch --depth=100000 origin

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer update --no-progress --ansi --prefer-lowest
            -   run: vendor/bin/phpunit
