name: Code Coverage

on:
    push:
        branches:
            - master

jobs:
    code_coverage:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            -
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.3
                    coverage: xdebug
                    tools: composer:v2

            -
                run: composer install --no-progress --ansi

            -
                run: |
                    composer require --dev nimut/phpunit-merger

                    vendor/bin/phpunit --coverage-php build/logs/rules.cov rules
                    vendor/bin/phpunit --coverage-php build/logs/packages.cov packages
                    vendor/bin/phpunit --coverage-php build/logs/tests.cov tests
                    vendor/bin/phpunit --coverage-php build/logs/utils.cov utils

                    vendor/bin/phpunit-merger coverage build/logs clover.xml

                    # Coveralls.io
                    composer require --dev php-coveralls/php-coveralls:^2.4
                    vendor/bin/php-coveralls --coverage_clover=clover.xml -v
                env:
                    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
