name: Code Analysis [no dev]

on:
    pull_request: null

jobs:
    matrix:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: 'Rector Recipe'
                        run: |
                            bin/rector init-recipe --ansi
                            bin/rector generate --ansi

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                    tools: composer:v2

            -   run: composer install --no-progress --ansi

            -   run: ${{ matrix.actions.run }}
