name: Rector Run

on:
    pull_request: null

jobs:
    matrix:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: Rector without Dev Dependencies
                        install: composer install --no-progress --ansi --no-dev
                        run: |
                            # must be removed, as local config is missing dev dependencies
                            rm phpstan-for-rector.neon
                            bin/rector list

        runs-on: ubuntu-latest
        name: ${{ matrix.actions.name }}

        steps:
            -   uses: actions/checkout@v2
            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4
                    coverage: none
                    tools: composer:v2

            -   run: ${{ matrix.actions.install }}

            -   run: ${{ matrix.actions.run }}
