name: Tests Root Directory

on: [pull_request, push]

jobs:
    finalize_classes:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                php_version: ['7.1', '7.2']

        name: "PHP ${{ matrix.php_version }}"

        steps:
            -   uses: actions/checkout@v2

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php_version }}
                    coverage: none

            # Validate the results are the expected ones
            -   run: |
                    wget -O phpunit https://phar.phpunit.de/phpunit-7.5.20.phar
                    php phpunit

